### ISSUE TITLE
Integration with Apache Mina not working as filesystem factory

### ISSUE THREAD

**Issue by rashmimaharana** [Upplication/Amazon-S3-FileSystem-NIO2#137]
Hi @carlspring

I have been trying to integrate this file system with apache mina sshd 2.12.1. But its failing. Here is the code snippet that i configured. 
If i pass the bucket name as plain with out any "/" , its throwing error as this.fileStore is null and when i passed the bucket with "/mybucket/" its connecting but giving error as below. I am using org.carlspring.cloud.aws:s3fs-nio:1.0,5

Any help. Anything i am missing here.

##ERROR 1
-nio2-thread-9] o.a.s.server.session.ServerSessionImpl   : exceptionCaught(ServerSessionImpl[rrmahar@/[0:0:0:0:0:0:0:1]:50619])[state=Opened] NullPointerException: Cannot invoke "org.carlspring.cloud.storage.s3fs.S3FileStore.name()" because "this.fileStore" is null

##ERROR 2
-nio2-thread-6] o.a.s.server.session.ServerSessionImpl   : exceptionCaught(ServerSessionImpl[rrmahar@/[0:0:0:0:0:0:0:1]:50662])[state=Opened] UnsupportedOperationException: Not a directory: s3://AKIAXMZ***@s3.amazonaws.com/mybucket/ 

##Configuration in apache mina
sshd.setFileSystemFactory(createFileSystemFactory("mybucket"));

##File System Factory to use inside apache mina

```
public FileSystemFactory createFileSystemFactory(String bucketName) throws IOException {
        Map<String, ?> env = ImmutableMap.<String, Object>builder().put(ACCESS_KEY, "AKIAX***")
                .put(SECRET_KEY, "hnBpn****")
                .put(REGION,"us-east-1")
                .build();
        FileSystem fileSystem = FileSystems.newFileSystem(URI.create("s3:///"),
                                                                    env,
                                                                    Thread.currentThread()
                                                                        .getContextClassLoader());
            Path bucketPath = fileSystem.getPath(bucketName);
            return new VirtualFileSystemFactory(bucketPath);
        }
```

**Comment by rashmimaharana** [comment]
wrong place.

**Comment by carlspring** [comment]
Yeah, this project is dead/
