### ISSUE TITLE
ReadAttributes throws a NPE when invoked on a bucket name path

### ISSUE THREAD

**Issue by pditommaso** [Upplication/Amazon-S3-FileSystem-NIO2#28]
When checking the *directory* flag for a path containing a single component that's the S3 bucket name the `readAttributes` method will fail. For example:

    Files.isDirectory( Paths.get("s3:///bucket-name/")  );

The following exception is raised:

    java.lang.NullPointerException: null
        at com.upplication.s3fs.S3FileSystemProvider.readAttributes(S3FileSystemProvider.java:485) ~[s3fs-0.2.8.jar:na]
        at java.nio.file.Files.readAttributes(Files.java:1737) ~[na:1.8.0_20]
        at java.nio.file.Files.isDirectory(Files.java:2192) ~[na:1.8.0_20]

  
The problem is that `objectSummary.getLastModified()` returns ``null`` 
https://github.com/Upplication/Amazon-S3-FileSystem-NIO2/blob/master/src/main/java/com/upplication/s3fs/S3FileSystemProvider.java#L485

This makes impossibile to list the bucket content. 

Do you have clue how this could be patched?

**Comment by pditommaso** [comment]
I would like to provide a pull request for this issue. However I'm wondering what  the best way to handle it. Do you think it makes sense to return a ``lastModifiedTime`` as 0 when that information is not returned for a bucket or is there an AWS API to retrieve it?

**Comment by sbeimin** [comment]
I believe the AWS spec suggests using the lasModifiedTime of the
contents... but that might be a very slow process.

**Comment by pditommaso** [comment]
Uh. It does not seem a viable alternative.

**Comment by sbeimin** [comment]
We might just want to return the create time...

**Comment by pditommaso** [comment]
It could be an option though it could be misleading. What about returning 0?

**Comment by jarnaiz** [comment]
Hi guys,

The ideal option is to read the content of the folder but I think this is a bad option from the point of view of performance.
I prefer to return a 0 so the developer can check this value and do something if he wants to get the real lastModified value.

Thanks!

**Comment by jarnaiz** [comment]
This error should be fixed in version 1.0.0-SNAPSHOT.
