### ISSUE TITLE
Check earlier if Path isn't a S3Path

### ISSUE THREAD

**Issue by salamanders** [Upplication/Amazon-S3-FileSystem-NIO2#42]
I tried getting started with a 
`Files.walkFileTree(rootPath, new SimpleFileVisitor<Path>() {`
And it took a while of digging through the trace to realize that even though I could pass in rootPath without a compile problem, a S3Path was required or else it would complain about the bucket missing.

**Comment by jarnaiz** [comment]
Im not sure whats the problem.

Can you send me a test or something?

Thanks!
