### ISSUE TITLE
Tag 1.0.1 release

### ISSUE THREAD

**Issue by hwellmann** [Upplication/Amazon-S3-FileSystem-NIO2#43]
There is a 1.0.1 release on Maven Central, but no matching tag in this repository.

**Comment by pditommaso** [comment]
I would suggest to maintain a changelog file as well.

**Comment by jarnaiz** [comment]
Im going to use git flow to have a good workflow and publish tags when a new release will be launched

**Comment by jarnaiz** [comment]
you can see now the lastest version with the changelog:
https://github.com/Upplication/Amazon-S3-FileSystem-NIO2/releases
