### ISSUE TITLE
Implement full java.nio.file.Path class

### ISSUE THREAD

**Issue by jarnaiz** [Upplication/Amazon-S3-FileSystem-NIO2#5]
Missing methods:
- [x] boolean startsWith(Path other)
- [x] boolean startsWith(String other)
- [x] boolean endsWith(Path other)
- [x] boolean endsWith(String other)
- [ ] Path toRealPath(LinkOption... options) throws IOException
- [ ] File toFile()
- [ ] WatchKey register(WatchService watcher, WatchEvent.Kind<?>[] events, WatchEvent.Modifier... modifiers) throws IOException
- [ ] WatchKey register(WatchService watcher, WatchEvent.Kind<?>... events) throws IOException

Notes:
- toFile is not possible.
- the register methods is out of roadmap (future release maybe)
- toRealPath study
- endsWith and startsWith are mandatory

**Comment by robmoore** [comment]
I'm using a library (Apache sshd) and it calls `S3Path.toRealPath(...)` which results in an unimplemented exception. Is looks like there was an intention to implement it (see above) but apparently it wasn't completed. If I understand correctly from the [JavaDocs](https://docs.oracle.com/javase/7/docs/api/java/nio/file/Path.html#toRealPath(java.nio.file.LinkOption...)) then it seems like it would simply return the absolute path as there's no concept of dot commands (eg, `..` or `.`) for S3 object key names.  

I'm curious with what conclusions you reached when trying to implement this.

**Comment by robmoore** [comment]
For what it's worth, another project (Githubfs) returns absolute path for `toRealPath`: https://github.com/gnodet/githubfs/blob/master/src/main/java/fr/gnodet/githubfs/GitHubPath.java#L297
