### ISSUE TITLE
S3SeekableByteChannel always uploads the data on close()

### ISSUE THREAD

**Issue by bgd42** [Upplication/Amazon-S3-FileSystem-NIO2#50]
Hi all,

When we create a `S3SeekableByteChannel` with option READ, then we should not upload the data on `close()`. I understand this functionality for other options (like WRITE) when we need to sync the changes with the remote S3, but in this case it is very confusing and decreases the performance of this implementation.

For now I have workarounds for this, but I think this issue deserves some attention in the future.

Cheers,
Bogdan

**Comment by jarnaiz** [comment]
I think the problem is fixed but I have some doubts about the StandardOpenOptions combinations.
If you see something wrong plz, tell me.

Thanks for your comments!
