### ISSUE TITLE
Custom directory for temporary files of S3SeekableByteChannel

### ISSUE THREAD

**Issue by okhamraiev** [Upplication/Amazon-S3-FileSystem-NIO2#53]
Currently(version 1.2.1) S3SeekableByteChannel uses system temp folder to store there temporary files. And if files is much bigger than /tmp folder size, only way to change this folder is set java.io.tmpdir that might be used by other parts of the application.
It would be nice to have some custom, independent from java.io.tmpdir, property to set temporary folder(or if it was not set - rollback to java.io.tmpdir)

**Comment by jarnaiz** [comment]
Hi,

thanks for the suggestion but is not a priority, I think is easy to do so if you want to collaborate with a PR I appreciate it a lot.

Cheers!
