### ISSUE TITLE
Access someone else's bucket?

### ISSUE THREAD

**Issue by guruxu** [Upplication/Amazon-S3-FileSystem-NIO2#54]
I'm getting `java.nio.file.NoSuchFileException` when I try to access a bucket shared with me from a different account by calling `fs.getPath("/shared-bucket-foo/test.txt")`. I'm able to access that file using AWS CLI. Is this supported?

**Comment by jarnaiz** [comment]
Im not sure and I dont have two accounts to test it easily. Maybe someone can help me with this? :)

Thanks for the feedback.
