### ISSUE TITLE
Incompatible as a FileSystem with Apache MINA SSHD

### ISSUE THREAD

**Issue by rossdrew** [Upplication/Amazon-S3-FileSystem-NIO2#56]
Creating an [Apache MINA](https://mina.apache.org/sshd-project/) SFTP server and using the `S3FileSystemProvider` doesn't work as MINA uses this `readAttributes`

`public Map<String, Object> readAttributes(Path path, String attributes, LinkOption... options) throws IOException`

which is not implemented and results in directories not being listed as expected.

**Comment by jarnaiz** [comment]
Hello Rossdrew,

thanks for your report.

I will try to implement the method this week, i think is not a hard task.

bye!

**Comment by rossdrew** [comment]
I've implemented it already in a rather hacky fashion and it then works with MINA.  I'm not really sure the best way to get file permissions though.

**Comment by jarnaiz** [comment]
If you can give me some tips/info about what kind of parameters (LinkOptions and attributes) need to read the Apache MINA. Can help me a lot :)

thanks!

**Comment by rossdrew** [comment]
My hacky method is as follows.  I've hard-coded the permissions as I'm not sure where I would get that information from at this point...

	public Map<String, Object> getAsMap(){
		Map<java.lang.String, java.lang.Object> map = new HashMap<>();
		map.put("fileKey",fileKey());
		map.put("isOther",isOther());
		map.put("isRegularFile",isRegularFile());
		map.put("isDirectory",isDirectory());
		map.put("isSymbolicLink",isSymbolicLink());
		map.put("size",size());
		map.put("lastModifiedTime",lastModifiedTime());
		map.put("lastAccessTime",lastAccessTime());
		map.put("permissions", PosixFilePermissions.fromString("rw-rw----"));
		//extended, uig, gid, owner, group, acl didn't seem to be required.

		return map;
	}

**Comment by jarnaiz** [comment]
Hello Rossdrew,

I hope version 1.3.0 solve your problem :)

Thanks for the feedback!

**Comment by rossdrew** [comment]
It doesn't I'm afraid, as, currently

`public <A extends BasicFileAttributes> A readAttributes(Path path, Class<A> type, LinkOption... options) throws IOException `

doesn't return permissions as an attribute, as required by MINA.

**Comment by jarnaiz** [comment]
Ups...
I think I missundertand you :/

What its the subclass needed for Apache MINA? s3fs only support BasicFileAttributes and S3FileAttributes and dont have the key "permissions".

In your first comment you talk to me about the method:

```java
public Map<String, Object> readAttributes(Path path, String attributes, LinkOption... options) throws IOException
```
And now:

```java
public <A extends BasicFileAttributes> A readAttributes(Path path, Class<A> type, LinkOption... options) throws IOException
```

Can you writte me some test or spike so we can reproduce your expected behaviour?

Sorry!

**Comment by rossdrew** [comment]
Yes, it requires the `Map<String, Object>` return type but your implementation calls the one with the `<A extends BasicFileAttributes>` return type, which has no __permissions__.

I was unaware that isn't included in basic attributes however.  It seems I have bigger problems here.  

[My project ](https://github.com/evogirossdrew/sftpSpokesman) is pretty small if you fancy running it to improve your project but at this point it's starting to seem like too much work for me to get this going :(

**Comment by rossdrew** [comment]
So FYI, I've gotten it working with MINA SSHD with a few hacks.  Namely adding permissions and a `FileChannel` option

```
public class S3FileSystemProviderWithFileChannel extends S3FileSystemProvider {
    /**
     * Just a FileChannel interface that points to a SeekableByteChannel
     */
    @Override
    public FileChannel newFileChannel(Path path,
                                      Set<? extends OpenOption> options,
                                      FileAttribute<?>... attrs)
            throws IOException
    {
        S3Path s3Path = toS3Path(path);
        return new S3FileChannel(s3Path, options);
    }

    /**
     * Private in original library so needs to be duplicated
     */
    private S3Path toS3Path(Path path) {
        Preconditions.checkArgument(path instanceof S3Path, "path must be an instance of %s", S3Path.class.getName());
        return (S3Path) path;
    }

    @Override
    public Map<String, Object> readAttributes(Path path, String attributes, LinkOption... options) throws IOException {
        Map<String, Object> attributeMap = super.readAttributes(path, attributes, options);

        if (attributeMap != null) {
            //XXX Hack as I have no idea how to get Amazon permissions as S3ObjectSummary (Amazon AWS SDK) doesn't contain any
            attributeMap.put("permissions", PosixFilePermissions.fromString("rw-rw----"));
        }

        return attributeMap;
    }
}
```

**Comment by jarnaiz** [comment]
Hi @rossdrew 

I implemented the method  readAttributes with PosixFileAttributes.class in tag 1.4.0. The conversion between S3ACLPermission and PosixPermission is very simple and limitated but I think you can use it without any workaround in your project and the implementation can be improved in the future.

cheers!

**Comment by robmoore** [comment]
I noticed that `S3FileSystem` still has code which doesn't include `posix` as a member.
```
    @Override
    public Set<String> supportedFileAttributeViews() {
        return ImmutableSet.of("basic");
    }
```
When the Mina sshd code attempts to check file attributes, it only sees `basic` so it skips the code path for posix attributes and fails due to an unimplemented `toFile()` method in S3Path. 

It seems like `posix` should be added as an option.

**Comment by robmoore** [comment]
Just wanted to bump this issue to make sure my comment was seen. Should I create another ticket?

**Comment by dtitov** [comment]
Same problem here as @robmoore has. Anyone?
