### ISSUE TITLE
Files.readAllBytes(..) creates an empty file of same name if file does not exist

### ISSUE THREAD

**Issue by ulmermark** [Upplication/Amazon-S3-FileSystem-NIO2#60]
Files.readAllBytes(..) creates an empty file of same name if file does not exist on S3

When passing a valid bucket but a file that does not exist within the bucket results in a temporary file being uploaded to S3.

Example:

Files.readAllBytes("bucketThatExists/folderThatExists/fileThatDoesNotExist)

**Comment by jarnaiz** [comment]
Im working on it.
Thanks for the feedback!

**Comment by jarnaiz** [comment]
Fixed in the tag: 1.4.1

Cheers
