### ISSUE TITLE
getFileSystemKey mismatch

### ISSUE THREAD

**Issue by sbeimin** [Upplication/Amazon-S3-FileSystem-NIO2#62]
When a S3FileSystem is created for an endpoint other than amazonws and the uri doesn't end with a '/' getFileSystemKey() returns Constants.S3_HOSTNAME.

Example:
`FileSystems.newFileSystem(URI.create("s3://access_key:secret_key@s3.mydomain.com:80"))`
results in a S3FileSystem being stored in the fileSystems map under key: "access_key:secret_key@s3.amazonaws.com" instead of "access_key:secret_key@s3.mydomain.com:80". When, lateron, `Paths.get(URI.create("s3://access_key:secret_key@s3.mydomain.com:80/mybucket/somefile"))` is called this results in a FileSystemNotFoundException.

**Comment by jarnaiz** [comment]
Hi Syte!

Thanks for the feedback and the PR #63 im going to check and try to fix it.

Cheers!

**Comment by sbeimin** [comment]
Hey Javier!,

PR already made :)

**Comment by jarnaiz** [comment]
Hi sbeimin,

Its a Travis limitation I use encrypted system env to pass the S3 access key and secret key for the Integration test:

* https://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables

**Comment by jarnaiz** [comment]
Fixed! thanks for your code and time :)
