### ISSUE TITLE
Call to S3Utils.getS3PosixFileAttributes() results in No Such Key (404) error

### ISSUE THREAD

**Issue by robmoore** [Upplication/Amazon-S3-FileSystem-NIO2#66]
I've modified my local copy of  S3Path so that it specifies a posix view as well as a basic view for file attribute views supported. This is required to support the integration with the Apache Mina sshd library. 

The Apache Mina code calls into `S3Utils.getS3PosixFileAttributes()`:
```
AccessControlList acl = client.getObjectAcl(bucketName, key);
```
When the key is a directory, I'm seeing a 404 error that isn't caught and results in a failure of the call to `getAcl()`. 

```
17:36:39.216 [sshd-SftpSubsystem-thread-1] DEBUG org.apache.http.headers - http-outgoing-45 >> GET /home/rob?acl HTTP/1.1
...
17:36:39.277 [sshd-SftpSubsystem-thread-1] DEBUG org.apache.http.headers - http-outgoing-45 << HTTP/1.1 404 Not Found
...
17:36:39.291 [sshd-SftpSubsystem-thread-1] DEBUG org.apache.http.wire - http-outgoing-45 << "<?xml version="1.0" encoding="UTF-8"?>[\n]"
17:36:39.293 [sshd-SftpSubsystem-thread-1] DEBUG org.apache.http.wire - http-outgoing-45 << "<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>home/rob</Key><RequestId>299958075A92ABEB</RequestId><HostId>dyCkn2DMRPbnABbGMlySbKlfoMZGSy7W40iK8TohjIrVz17oGsJThk7O/Z+8qx5rgpCyJUFUMso=</HostId></Error>[\r][\n]"
```

As in other places in the code, there is a first attempt to query the path as a file. However, in this case the 403 isn't caught and a subsequent request treating the path as a directory isn't performed.

**Comment by jarnaiz** [comment]
Hi robmoore,

Thanks for your feedback, you are right, the getS3PosixFileAttributes method is not working with folders and return a 404 error.

I think it is fixed in the 1.5.2 version. 

Cheers!
