### ISSUE TITLE
META-INF/services/java.nio.file.spi.FileTypeDetector references non-existing class

### ISSUE THREAD

**Issue by sbeimin** [Upplication/Amazon-S3-FileSystem-NIO2#78]
src/main/resources/META-INF/services/java.nio.file.spi.FileTypeDetector points the File type detection system of NIO to the class com.upplication.s3fs.util.FileTypeDetector which does not exist.

**Comment by febner** [comment]
+1

**Comment by wwurzer-twyn** [comment]
results in java.lang.NoClassDefFoundError: Could not initialize class java.nio.file.Files$FileTypeDetectors

**Comment by Gilis95** [comment]
Yes, same here...

**Comment by jarnaiz** [comment]
I am currently working on this issue and on other old ones too!

**Comment by jarnaiz** [comment]
Hello,

I remove the src/main/resources/META-INF/services/java.nio.file.spi.FileTypeDetector  so the problem must be solved

Thanks for the feedback!
